export const jobList = [
  {
    id: 1,
    jobtitle: "Senior Product Designer",
    imagePath: "./assests/images/76ers.png",
    company: "ATB TECH",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",

    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description:
      "yuiopewreydffdgfuietryuruiokfncbvfdfgetryuutiottkkmvbfgdfertrytuiooymncvfdfertrtytuio",
  },
  {
    id: 2,
    jobtitle: "Backend Developer",
    imagePath: "./assests/images/76ers.png",
    company: "PACKWAY",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",

    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description:
      "yuiopewreydffdgfuietryuruiokfncbvfdfgetryuutiottkkmvbfgdfertrytuiooymncvfdfertrtytuio",
  },
  {
    id: 3,
    jobtitle: "Digital Marketer",
    imagePath: "./assests/images/76ers.png",
    company: "CANONICAL ",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",

    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description:
      "yuiopewreydffdgfuietryuruiokfncbvfdfgetryuutiottkkmvbfgdfertrytuiooymncvfdfertrtytuio",
  },
  {
    id: 4,
    jobtitle: "Sales Manager",
    imagePath: "./assests/images/76ers.png",
    company: "ZIPLINE",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",
    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description: "boy girl b",
  },
  {
    id: 5,
    jobtitle: "DevOps Expert",
    imagePath: "./assests/images/76ers.png",
    company: "TOKEN METRICS",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",
    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description: "boy girl b",
  },
  {
    id: 5,
    jobtitle: "QA/QC Analyst",
    imagePath: "./assests/images/76ers.png",
    company: "RENMONEY",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",
    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description: "boy girl b",
  },
  {
    id: 7,
    jobtitle: "Animation Specialist",
    imagePath: "./assests/images/76ers.png",
    company: "CANONICAL",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",
    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description: "boy girl b",
  },
  {
    id: 8,
    jobtitle: "IT Specialist",
    imagePath: "./assests/images/76ers.png",
    company: "KINGMAKERS",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",
    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description: "boy girl b",
  },
  {
    id: 9,
    jobtitle: "Customer Experience",
    imagePath: "./assests/images/76ers.png",
    company: "DELOITTE ",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",
    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description: "boy girl b",
  },
  {
    id: 10,
    jobtitle: "Operations Manager",
    imagePath: "./assests/images/76ers.png",
    company: "SENTZ GLOBAL ",
    location: "Lagos, Nigeria",
    askingAmount: "₦1,000,000.00",
    amount: "450,000",
    "education level": "Graduate",
    "experience level": "professional",
    "job type": "Remote",
    "job role type": "full time",
    description: "boy girl b",
  },
];
